// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDET9T_8owYO4A9SDcIUlSLNAH4pIc4nb0',
    appId: '1:54514655667:web:db405303fbe2ec2d452bc6',
    messagingSenderId: '54514655667',
    projectId: 'universitysport-671c2',
    authDomain: 'universitysport-671c2.firebaseapp.com',
    storageBucket: 'universitysport-671c2.firebasestorage.app',
    measurementId: 'G-1PX57E1PQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUblINZLYOS3LTH6YkBE3mGiiQQAvSW8',
    appId: '1:54514655667:android:dc881aeee137953b452bc6',
    messagingSenderId: '54514655667',
    projectId: 'universitysport-671c2',
    storageBucket: 'universitysport-671c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZFfWJMZH9Gzd0iyvIrSlJRDfc8AbEXg',
    appId: '1:54514655667:ios:f5d3175e20fdf28f452bc6',
    messagingSenderId: '54514655667',
    projectId: 'universitysport-671c2',
    storageBucket: 'universitysport-671c2.firebasestorage.app',
    iosBundleId: 'com.seiyun.sports.unisport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZFfWJMZH9Gzd0iyvIrSlJRDfc8AbEXg',
    appId: '1:54514655667:ios:f5d3175e20fdf28f452bc6',
    messagingSenderId: '54514655667',
    projectId: 'universitysport-671c2',
    storageBucket: 'universitysport-671c2.firebasestorage.app',
    iosBundleId: 'com.seiyun.sports.unisport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDET9T_8owYO4A9SDcIUlSLNAH4pIc4nb0',
    appId: '1:54514655667:web:3339dd1fe66564ba452bc6',
    messagingSenderId: '54514655667',
    projectId: 'universitysport-671c2',
    authDomain: 'universitysport-671c2.firebaseapp.com',
    storageBucket: 'universitysport-671c2.firebasestorage.app',
    measurementId: 'G-MDGXGXBCWL',
  );
}
